### ISSUE TITLE
[Bug]: "Can not create a folder inside a [SOURCE]" when writing table into object storage

### ISSUE THREAD

**Issue by mxmarg** [dremio/dbt-dremio#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to create a materialized table in a not yet existing folder, Dremio dbt throws the following error message:
`dbt.adapters.dremio.api.rest.error.DremioBadRequestException: Bad request:: (400 Client Error: Bad Request for url: http://<DREMIO_ENDPOINT>/api/v3/catalog): ({"errorMessage":"Can not create a folder inside a [SOURCE].","moreInfo":""})`
 
 The current workaround is to create the data source folder outside of dbt.

### Expected Behavior

Since Dremio is able to write Iceberg tables while creating new directories, this error should not occur.
Likely, Dremio is using the catalog REST API method to create a folder in the Semantic Layer, which is throws an error, since it is not possible to create Semantic Layer folders on an object storage in Dremio.

### Steps To Reproduce

{{ config(
    materialized="table",
    database="DEBUG_SPACE",
    schema="Debug",
    object_storage_source="source_name",
    object_storage_path="container_name.NOT_YET_EXISTING_FOLDER"
) }}
SELECT 1

### Environment

```markdown
- OS: macOS
- dbt-dremio: 1.5.0
- Dremio Software: 24.1.1
- Dremio Cloud: N/A
```

### Relevant log output

```shell
ddl_dbt_model git:(main) ✗ dbt run -t sandbox -s models/Debug
10:59:54  Running with dbt=1.5.2
10:59:54  Registered adapter: dremio=1.5.0
10:59:54  Found 151 models, 5 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 38 sources, 0 exposures, 0 metrics, 0 groups
10:59:54  
10:59:56  
10:59:56  Finished running  in 0 hours 0 minutes and 1.59 seconds (1.59s).
10:59:56  Encountered an error:
Bad request:: (400 Client Error: Bad Request for url: http://<DREMIO_ENDPOINT>/api/v3/catalog): ({"errorMessage":"Can not create a folder inside a [SOURCE].","moreInfo":""})
10:59:56  Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 250, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/main.py", line 565, in run
    results = task.run()
              ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/runnable.py", line 443, in run
    result = self.execute_with_hooks(selected_uids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/runnable.py", line 405, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/run.py", line 446, in before_run
    self.create_schemas(adapter, required_schemas)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/runnable.py", line 562, in create_schemas
    create_future.result()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/utils.py", line 464, in connected
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/runnable.py", line 526, in create_schema
    adapter.create_schema(relation)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/impl.py", line 66, in create_schema
    self.connections.create_catalog(database, schema)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/connections.py", line 220, in create_catalog
    self._create_folders(database, schema, api_parameters)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/connections.py", line 244, in _create_folders
    create_catalog_api(api_parameters, folder_json)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/api/rest/endpoints.py", line 216, in create_catalog_api
    return _post(
           ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/api/rest/endpoints.py", line 65, in _post
    return _check_error(response, details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/dremio/api/rest/endpoints.py", line 118, in _check_error
    raise DremioBadRequestException("Bad request:" + details, error, response)
dbt.adapters.dremio.api.rest.error.DremioBadRequestException: Bad request:: (400 Client Error: Bad Request for url: http://<DREMIO_ENDPOINT>/api/v3/catalog): ({"errorMessage":"Can not create a folder inside a [SOURCE].","moreInfo":""})
```

**Comment by donatobarone** [comment]
interested as well, but if you don't mind @mxmarg I have a question, I have been trying to use the materialized=table configuraiton and the table is created in dremio as expected, in the location where it is supposed to but the dbt run command never finishes, it seems that it hangs, have you ever experienced this?

**Comment by mxmarg** [comment]
I have not experienced this particular behaviour, no. Is it reproducible? If yes, you could probably open a separate bug. 
The issue I described occurs during preparation, probably because dbt tries to run the following API call against a data source path, which is not allowed: https://docs.dremio.com/software/api/catalog/folder/#creating-a-folder

**Comment by Conq1** [comment]
> interested as well, but if you don't mind @mxmarg I have a question, I have been trying to use the materialized=table configuraiton and the table is created in dremio as expected, in the location where it is supposed to but the dbt run command never finishes, it seems that it hangs, have you ever experienced this?
I hope someone can clean these thread, but to me it sounds like you issue is this one: https://github.com/dremio/dbt-dremio/issues/176 
Basically it retrieves the table you just created, which make it look like it hangs.

**Comment by fabrice-etanchaud** [comment]
Hi all, yes, the adapter should not try to create schemas in writable sources, as dremio will do it itself.
The problem is dremio segretates tables and views, but for dbt they all lives in common schemas.
All non existing dbt 'schemas' will be created beforehand at dbt start. I am not sure the adapter has a way to tell dbt not to issue a create_schema for missing source directories.

**Comment by mxmarg** [comment]
After having tested the new dbt-dremio release 1.5.1, I was no longer able to reproduce this error

**Comment by mxmarg** [comment]
Sorry for the confusion, but I must have missed something in the repro, as the bug is still valid.

As per @fabrice-etanchaud 's suggestion, the command works, if we add additional error handling like the following:
 ```
   def _create_folders(self, database, schema, api_parameters):
        temp_path_list = [database]
        for folder in schema.split("."):
            temp_path_list.append(folder)
            folder_json = self._make_new_folder_json(temp_path_list)
            try:
                create_catalog_api(api_parameters, folder_json)
            except DremioAlreadyExistsException:
                logger.debug(f"Folder {folder} already exists.")
            except DremioBadRequestException as e:
                if "Can not create a folder inside a [SOURCE]" in e.message:
                    logger.debug(f"Ignoring {e}")
                else:
                    raise DremioBadRequestException(e)
```
